language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install python3
  - sudo apt-get install bc

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install gcc-arm-linux-gnueabihf 

before_script:
  - export DST_PROJECT=$PWD
  - echo $DST_PROJECT

  - export SOURCE_BRANCH="4.14"
  - export SOURCE_VERSION="rc1"
  - export SOURCE_PLATFORM="bone1"

  - wget -c https://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - export CC=$DST_PROJECT/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
  - ${CC}gcc --version

  - wget https://github.com/RobertCNelson/linux-stable-rcn-ee/archive/v$SOURCE_BRANCH-$SOURCE_VERSION.tar.gz
  - tar xf v$SOURCE_BRANCH-$SOURCE_VERSION.tar.gz

  - cd $DST_PROJECT/linux-stable-rcn-ee-$SOURCE_BRANCH-$SOURCE_VERSION

  - make -j3 mrproper ARCH=arm CROSS_COMPILE=${CC}
  - wget -c "http://rcn-ee.net/deb/jessie-armhf/v$SOURCE_BRANCH.0-$SOURCE_VERSION-$SOURCE_PLATFORM/defconfig" -O .config
  - make -j3 modules ARCH=arm CROSS_COMPILE=${CC}

  - cd $DST_PROJECT/
  - sudo chmod +x $DST_PROJECT/scripts/install_IceStorm.sh
  - sudo sh $DST_PROJECT/scripts/install_IceStorm.sh

  - cd $DST_PROJECT/
  - sudo wget -c https://raw.githubusercontent.com/RobertCNelson/tools/master/pkgs/dtc.sh
  - sudo chmod +x dtc.sh
  - sudo ./dtc.sh

script:
  - make -C $DST_PROJECT/drivers/ ARCH=arm CROSS_COMPILE=${CC}
  - sudo perl $DST_PROJECT/linux-stable-rcn-ee-$SOURCE_BRANCH-$SOURCE_VERSION/scripts/checkpatch.pl --no-tree -f drivers/*.c

  - make all -C $DST_PROJECT/examples

  - make -C $DST_PROJECT/bridge_lib/ ARCH=arm CROSS_COMPILE=${CC}

  - cd $DST_PROJECT/DTS
  - sudo dtc -O dtb -o BW-ICE40Cape-00A0.dtbo -b 0 -@ BW-ICE40Cape-00A0.dts
  - sudo dtc -O dtb -o BW-SPI-ICE40Cape-00A0.dtbo -b 0 -@ BW-SPI-ICE40Cape-00A0.dts
  - sudo dtc -O dtb -o BW-GPIO-ICE40Cape-00A0.dtbo -b 0 -@ BW-GPIO-ICE40Cape-00A0.dts
  - sudo dtc -O dtb -o BW-PWM-ICE40Cape-00A0.dtbo -b 0 -@ BW-PWM-ICE40Cape-00A0.dts
  - sudo dtc -O dtb -o BW-I2C-ICE40Cape-00A0.dtbo -b 0 -@ BW-I2C-ICE40Cape-00A0.dts

